import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

describe('compact floating widget', () => {
  it('uses a side-card floating widget with separate drag and click zones', () => {
    const component = readFileSync(resolve(process.cwd(), 'src/renderer/App.vue'), 'utf8')
    const styles = readFileSync(resolve(process.cwd(), 'src/renderer/styles.css'), 'utf8').replace(/\r\n/g, '\n')
    const main = readFileSync(resolve(process.cwd(), 'src/main/index.ts'), 'utf8')
    const preload = readFileSync(resolve(process.cwd(), 'src/preload/index.ts'), 'utf8')
    const preloadWriter = readFileSync(resolve(process.cwd(), 'scripts/write-preload-cjs.cjs'), 'utf8')
    const orbRule = styles.match(/\.widget-shell \.widget-orb \{[\s\S]*?\}/g)?.at(-1)
    const actionRule = styles.match(/\.widget-shell \.widget-orb-action \{[\s\S]*?\}/g)?.at(-1)
    const expandedRule = styles.match(/\.widget-shell\.is-expanded \.widget-orb \{[\s\S]*?\}/g)?.at(-1)

    expect(main).toContain('const widgetCompactSize = { width: 104, height: 104 }')
    expect(main).toContain('const widgetExpandedSize = { width: 337, height: 132 }')
    expect(main).toContain('let widgetExpanded = false')
    expect(main).toContain('expanded: widgetExpanded')
    expect(main).toContain("webContents.send('widget:expandedChanged', widgetExpanded)")
    expect(main).toContain('new WidgetInteractionController()')
    expect(main).toContain("ipcMain.on('widget:pointer'")
    expect(preload).toContain('sendWidgetPointer')
    expect(preloadWriter).toContain("sendWidgetPointer: (input) => ipcRenderer.send('widget:pointer', input)")
    expect(component).toContain("document.addEventListener('pointerdown', handleWidgetPointer, true)")
    expect(main).not.toContain("webContents.send('widget:nativeClick')")
    expect(main).toContain("ipcMain.handle('widget:moveBy'")
    expect(main).toContain('widgetWindow.setIgnoreMouseEvents(false)')
    expect(main.match(/widgetWindow\.setIgnoreMouseEvents\(false\)/g)?.length).toBeGreaterThanOrEqual(2)
    expect(main).toContain("backgroundColor: '#00000000'")
    expect(component).toContain('<em>5H</em>')
    expect(component).toContain('class="widget-orb-action"')
    expect(component).not.toContain('@click.stop="handleWidgetDomClick"')
    expect(preload).toContain('onWidgetExpandedChanged')
    expect(preload).not.toContain('onWidgetNativeClick')
    expect(component).toContain('onWidgetExpandedChanged')
    expect(component).toContain("window.addEventListener('resize', syncWidgetExpanded)")
    expect(component).not.toContain('startWidgetDrag')
    expect(component).not.toContain('moveWidgetDrag')
    expect(component).not.toContain('endWidgetDrag')
    expect(component).toContain('class="widget-flyout-card"')
    expect(component).toContain('class="widget-quota-block is-five"')
    expect(component).toContain('class="widget-quota-block is-seven"')
    expect(component).toContain('class="widget-quota-progress"')
    expect(component).toContain('resetAtDisplay(fiveHourWindow)')
    expect(component).toContain('class="widget-target-layout"')
    expect(component).toContain('class="widget-target-footer"')
    expect(component).toContain('class="widget-reset-card-button"')
    expect(component).not.toContain('class="widget-collapse"')
    expect(component).not.toContain('class="widget-warning-copy"')
    expect(component).not.toContain('class="widget-segmented"')
    expect(component).not.toContain('@mouseenter="handleWidgetEnter"')
    expect(component).not.toContain('@mouseleave="handleWidgetLeave"')
    expect(component).not.toContain('@pointerenter="handleWidgetEnter"')
    expect(component).not.toContain('class="widget-orb-status"')
    expect(component).not.toContain('class="widget-orb-secondary-pill"')
    expect(component).toContain('background: quotaColor(sevenDayWindow)')
    expect(component).toContain("'is-warning': widgetPrimaryPercent !== null && widgetPrimaryPercent < 20")
    expect(component).toContain("'is-disconnected': widgetPrimaryPercent === null")
    expect(component).toContain('5小时额度')
    expect(component).toContain('7天额度')
    expect(styles).toContain('width: 284px !important')
    expect(styles).toContain('padding: 12px 4px 8px 58px !important')
    expect(styles).toContain('height: 6px !important')
    expect(styles).toContain('font-size: 10px !important')
    expect(styles).toContain('.widget-flyout-card > .widget-target-layout')
    expect(styles).toContain('color: #aebbd0;')
    expect(styles).toContain('border-top: 1px solid rgba(94, 124, 166, 0.1);')
    expect(styles).toContain('.widget-quota-block')
    expect(styles).toContain('.widget-quota-progress-fill')
    expect(styles).toContain('.widget-meta-footer')
    expect(styles).toContain('.widget-quota-block.is-five.is-low')
    expect(styles).toContain('width: 72px !important')
    expect(styles).toContain('height: 72px !important')
    expect(styles).toContain('.widget-shell .widget-orb.is-warning')
    expect(styles).toContain('.widget-shell .widget-orb.is-disconnected')
    expect(styles).toContain('.widget-shell:not(.is-expanded) .widget-panel {\n  display: none !important;')
    expect(styles).toContain('.widget-panel,\n.widget-flyout-card {\n  -webkit-app-region: no-drag !important;')
    expect(orbRule).toContain('-webkit-app-region: no-drag !important')
    expect(orbRule).not.toContain('0 0 0 5px')
    expect(actionRule).toContain('-webkit-app-region: no-drag')
    expect(actionRule).toContain('inset: 14px')
    expect(actionRule).toContain('display: block')
    expect(actionRule).toContain('pointer-events: auto !important')
    expect(styles).toContain('pointer-events: none !important')
    expect(styles).toContain('.widget-shell {\n  -webkit-app-region: no-drag !important;')
    expect(expandedRule).not.toContain('opacity: 0')
    expect(expandedRule).toContain('width: 88px !important')
    expect(expandedRule).toContain('height: 88px !important')
  })
})
